version: '3'

vars:
  # Default image name and tag
  ACR_REGISTRY: "jairo"
  IMAGE_NAME: "lk-hubcoworkhi-frontdesk-agent"
  IMAGE_TAG: "latest"
  AZ_SUBSCRIPTION_ID: "553b3c7a-c3b2-40de-8037-ffe396f30141"

  # Python environment settings
  VENV_DIR: ".venv"
  PYTHON: "python3"
  PIP: "pip3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: false

  # Python Virtual Environment tasks
  venv-setup:
    desc: Set up Python virtual environment and install dependencies
    cmds:
      - python3 -m venv .venv
      - source .venv/bin/activate
      - .venv/bin/pip install --upgrade pip
      - .venv/bin/pip install -r requirements.txt        
    silent: false

  venv-clean:
    desc: Remove virtual environment
    cmds:
      - rm -rf .venv
      - echo "Virtual environment removed"
    silent: false

  # Agent tasks
  agent-run:
    desc: Run the context variable agent
    cmds:
      - .venv/bin/python agent.py dev
    silent: false

  agent-download-models:
    cmds:
      - .venv/bin/python agent.py download-files
    desc: Download required ML models

  # Docker tasks
  docker-build:
    cmds:
      - docker build  --platform linux/amd64 -t "{{.ACR_REGISTRY}}.azurecr.io/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}" .
    desc: Build the Docker image

  docker-push:
    cmds:
      - docker push "{{.ACR_REGISTRY}}.azurecr.io/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
    desc: Push the Docker image to the registry

  docker-run-with-env:
    cmds:
      - docker run --rm -it --env-file .env.local "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
    desc: Run the Docker container with environment variables from .env.local

  docker-clean:
    cmds:
      - docker rmi "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}" 2>/dev/null || true
    desc: Remove the Docker image

  docker-list-images:
    cmds:
      - docker images "{{.IMAGE_NAME}}"
    desc: List all Docker images for this project

  # Azure tasks
  az-login:
    desc: Log in to Azure CLI
    cmds:
      - az login
    silent: false

  acr-login:
    desc: Log in to Azure Container Registry
    cmds:
      - az acr login --name "{{.ACR_REGISTRY}}"
    silent: false

  az-list-subscriptions:
    desc: List Azure subscriptions in table format
    cmds:
      - az account list --output table
    silent: false

  az-set-subscription:
    desc: Set the active Azure subscription
    cmds:
      - az account set --subscription "{{.AZ_SUBSCRIPTION_ID}}"
    silent: false
